#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login_check

gesdinet_jwt_refresh_token:
  path: /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

api_users_register:
  path:     /api/users/register
  methods:  POST
  controller: App\Controller\AuthController:register

api_users_search:
  path:     /api/users/search
  methods:  POST
  controller: App\Controller\SearchController:search

api_users_bouquet:
  path:     /api/users/{id}/bouquet
  methods:  GET
  controller: App\Controller\BouquetController:bouquet